### ISSUE TITLE
Blind booking mode ?

### ISSUE THREAD

**Issue by laurent-d** [vanadiuz/table-reservation#3]
Hi !

Your apps looks fantastic, do you think you will implement a blind booking mode wich select table depending of number of guest without display the room map ?
Thanks a lot for your work, do not hesitates if you want a french translation.

Cheers

**Comment by vanadiuz** [comment]
Hi Laurent,

It's quite feasible! I do not know when I can implement it, because now I'm working on a new plugin. But if you still want to make a fork with such feature, then all necessary changes need to be done only in the file app.vue.
And I apologize for the awkwardness of my code, it is very amateur 🤷‍
