### ISSUE TITLE
Language Dutch

### ISSUE THREAD

**Issue by zwagersbovenkarspel** [vanadiuz/table-reservation#36]
Hi There, 

I am hoping anyone can help out! I am not a developer, but a user of the plug-in. I have translated most of the fields here: https://translate.wordpress.org/projects/wp-plugins/table-reservations/dev/nl/default/

I know this pug-in is no longer supported in Wordpress, but it works fantastic and it would be great if someone here can create the translation in an update. I live in an area where English is not preferred and it would be great if all these fields would be visible in Dutch. please see the active page: https://zwagers.net/reserveren

Appreciate any help! Thanks in advance!

Have a great day

Eric

**Comment by ahmetoktay1234** [comment]
*01/06/2020*





Vanadiuz / Table-Reservation



Dear Eric,



I'm not a developer either, so I would love to, but unfortunately I can't
help you.

I've been looking for this plugin for a very long time, but like you said
it is no longer supported in Wordpress.



Although I could not help you, I will be very grateful if you send me this
plugin.



Looking forward to hear from you soon.



Yours truly.



Wilfried Hermann Nothof



*J*

e-mail: ahmetoktay.yenicerioglu@gmail.com


zwagersbovenkarspel <notifications@github.com>, 5 Oca 2020 Paz, 11:51
tarihinde şunu yazdı:

**Comment by Polundra** [comment]
Eric, I just send you an e-mail. The Dutch translation is included as attachement.

**Comment by RubenHoms** [comment]
@Polundra or @zwagersbovenkarspel could you share the Dutch translation with me (or in this thread) so I can use it as well? Would be much appreciated! :+1:

**Comment by Polundra** [comment]
Hello Ruben,

 

For now, as attachment, my Dutch translation has been included. 

 

Honestly, I was under the impression (sadly!) that this plugin development has stopped. Because last week I had a short e-mail conversation with Ivan where he told me the plugin development is suspended.

Fyi, I was hoping this plugin could be used as full blown addon for Modern Events Calendar. And I did inform webnus about this, also! As that would be some awesome module! 

Because I did not get any reply (yet). And because I was on tight time schedule, I started my own effort in full code translation. Unfortunately, over and over again the result is a critical error.

 

Anyhow. There is some minor spelling mistake in the original code. There could be more, but I did translate and went on…

Meta_box at line 118 and 129 

Wrong  - tremtr_reservatin_default_hidden_meta_boxes

correct - tremtr_reservation_default_hidden_meta_boxes

Hopefully my website will be online and running again tomorrow. I will then test a little further, whiter or not if this translation is properly done towards the original target audience. I think it is, but still it might have some tweaks – that might get the owner in trouble. Like time-format: “mmmmm, d” has been set into “l j F Y”

 

Regards,

 

 

Wouter-Jan Kok

 

p.s. Are you currently developing this plugin?   

 

 

Van: Ruben Homs <notifications@github.com> 
Verzonden: donderdag 7 mei 2020 00:35
Aan: vanadiuz/table-reservation <table-reservation@noreply.github.com>
CC: Wouter-Jan Kok <wjkok@home.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [vanadiuz/table-reservation] Language Dutch (#36)

 

@Polundra <https://github.com/Polundra>  or @zwagersbovenkarspel <https://github.com/zwagersbovenkarspel>  could you share the Dutch translation with me (or in this thread) so I can use it as well? Would be much appreciated! 👍

**Comment by RubenHoms** [comment]
@Polundra I think you forgot the attachment, haha! :) Not sure if you can send attachments through email, an alternative would be to host it in a [gist](https://gist.github.com/). Much appreciated!

It could be that the development has stopped, but that doesn't mean it won't work anymore. And since it's open source anyone can come along and adopt the project. I just stumbled upon this project yesterday as I was trying to find a reservation system now that the government requires it for cafe's/restaurants from the 1st of June.

Assuming you're a dutch restaurant/cafe owner, these open source solutions really help out a great deal in these times. So thanks a lot for this @vanadiuz!

**Comment by Polundra** [comment]
Darn! Second try. The plugin does work out of the box, no problems.

 

Tip about cropping the ‘table’ layout. Make this if possible rectangular. I started out with very small row and that did not workout nicely.

 

Best wishes!

 

Wouter-Jan Kok

 

 

 

 

 

Van: Ruben Homs <notifications@github.com> 
Verzonden: donderdag 7 mei 2020 10:28
Aan: vanadiuz/table-reservation <table-reservation@noreply.github.com>
CC: Wouter-Jan Kok <wjkok@home.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [vanadiuz/table-reservation] Language Dutch (#36)

 

@Polundra <https://github.com/Polundra>  I think you forgot the attachment, haha! :) Not sure if you can send attachments through email, an alternative would be to host it in a gist <https://gist.github.com/> . Much appreciated!

It could be that the development has stopped, but that doesn't mean it won't work anymore. And since it's open source anyone can come along and adopt the project. I just stumbled upon this project yesterday as I was trying to find a reservation system now that the government requires it for cafe's/restaurants from the 1st of June.

Assuming you're a dutch restaurant/cafe owner, these open source solutions really help out a great deal in these times. So thanks a lot for this @vanadiuz <https://github.com/vanadiuz> !

**Comment by RubenHoms** [comment]
@Polundra nope, still no attachment! I'd suggest uploading it to gist.github.com since clearly email attachments don't work. :stuck_out_tongue:

**Comment by Polundra** [comment]
For now, I only change proper working code into broken code.

Sorry, I do not know how to use gist. Perhaps I might find that a useful skill, someday.  

 

 

Regards,

 

 

Wouter-Jan Kok

wjkok@home.nl <mailto:wjkok@home.nl> 

 

 

 

 

Van: Ruben Homs <notifications@github.com> 
Verzonden: donderdag 7 mei 2020 10:42
Aan: vanadiuz/table-reservation <table-reservation@noreply.github.com>
CC: Wouter-Jan Kok <wjkok@home.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [vanadiuz/table-reservation] Language Dutch (#36)

 

@Polundra <https://github.com/Polundra>  nope, still no attachment! I'd suggest uploading it to gist.github.com since clearly email attachments don't work. 😛

**Comment by zwagersbovenkarspel** [comment]
Guys,

Just out of curiousity, I am using the online wordpress and tried a file manager to upload the files, but it is blocked. any workaround?

Thanks,

Eric



On 7 May 2020, at 10:48, Wouter-Jan Kok <notifications@github.com <mailto:notifications@github.com> > wrote:


For now, I only change proper working code into broken code.

Sorry, I do not know how to use gist. Perhaps I might find that a useful skill, someday. 

 

 

Regards,

 

 

Wouter-Jan Kok

wjkok@home.nl <mailto:wjkok@home.nl> <mailto:wjkok@home.nl <mailto:wjkok@home.nl> > 

 

 

 

 

Van: Ruben Homs <notifications@github.com <mailto:notifications@github.com> > 
Verzonden: donderdag 7 mei 2020 10:42
Aan: vanadiuz/table-reservation <table-reservation@noreply.github.com <mailto:table-reservation@noreply.github.com> >
CC: Wouter-Jan Kok <wjkok@home.nl <mailto:wjkok@home.nl> >; Mention <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Onderwerp: Re: [vanadiuz/table-reservation] Language Dutch (#36)

 

@Polundra <https://github.com/Polundra> nope, still no attachment! I'd suggest uploading it to gist.github.com <http://gist.github.com> since clearly email attachments don't work. 😛

**Comment by RubenHoms** [comment]
@Polundra @zwagersbovenkarspel  I've made the translations for this plugin myself yesterday and just created a pull request so it can be merged and used by everyone. (#38)

@zwagersbovenkarspel Will need more info on what you're trying to do here. Uploading what to what and why? Did you follow the instructions on how to set this up in the [README](https://github.com/vanadiuz/table-reservation#build-process-hammer)?

**Comment by zwagersbovenkarspel** [comment]
Hi,

I have had this plug-in operational for over a year, adding languages ,needs the language files to be uploaded to the public wordpress site. in order to do that the two files must be added to the site. There is no way to add these files as far as i can see.

Eric



On 8 May 2020, at 12:58, Ruben Homs <notifications@github.com <mailto:notifications@github.com> > wrote:


@Polundra @zwagersbovenkarspel I've made the translations for this plugin myself yesterday and just created a pull request so it can be merged and used by everyone. (#38)

@zwagersbovenkarspel Will need more info on what you're trying to do here. Uploading what to what and why? Did you follow the instructions on how to set this up in the README?

**Comment by RubenHoms** [comment]
@zwagersbovenkarspel I don't think there's a way to do it through the WordPress admin panel (haven't found one myself yet), but you can do it by placing it in the right directory on the server that's running your website, that's how I did it. It even says so in the [FAQ](https://github.com/vanadiuz/table-reservation#faq).

Just place the `.po` & `.mo` files in `/path/to/wordpress/wp-content/languages/plugins` so you'll end up with `/path/to/wordpress/wp-content/languages/plugings/tremtr-nl_NL.mo` and `/path/to/wordpress/wp-content/languages/plugins/tremtr-nl_NL.po`. Usually `/path/to/wordpress` is something like `/var/www/html` for nginx/apache webservers.

**Comment by RubenHoms** [comment]
This issue can now be closed @zwagersbovenkarspel, the translations were merged into master by #38. :ok_hand:
