### ISSUE TITLE
Get in touch

### ISSUE THREAD

**Issue by lblase** [vanadiuz/table-reservation#40]
Hi, 

I would like to get in touch with the developers. 
I haven't found any support mail that's why I'm writing here.

Let me know,
Thanks.

**Comment by Polundra** [comment]
Hello Benny, 

 

Sorry, I do not know if I’m allowed to share his e-mail. It is in public available (if you take some time for search).

 

Regards,

 

Wouter-Jan Kok

 

------------------------------------------- 

Two weeks ago, I received this:

 
Dear Wouter,
 
Unfortunately, the plugin development is suspended. I can’t help you.
 
Best regards,
Ivan Novikau
 

 

 

 

Van: Benny <notifications@github.com> 
Verzonden: donderdag 14 mei 2020 18:00
Aan: vanadiuz/table-reservation <table-reservation@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [vanadiuz/table-reservation] Get in touch (#40)

 

Hi,

I would like to get in touch with the developers.
I haven't found any support mail that's why I'm writing here.

Let me know,
Thanks.

**Comment by lblase** [comment]
You can contact me on telegram @help_desk_pro and you can send me there the email address.

If you want.

Thanks!
